# Adapted from https://github.com/yjbanov/flutter_travis_sample

os: linux

sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid

cache:
  directories:
    - $HOME/.pub-cache

install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor

jobs:
  include:
    - stage: test
      name: "Linting"
      script: ./flutter/bin/flutter analyze
    # - script: ./flutter/bin/flutter test
    #   name: "Unit Tests"
    # - stage: build
    #   name: "Build Android"
    #   script:
