language: dart
dart: stable

addons:
  apt:
    packages:
      - lib32stdc++6

install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor

cache:
  directories:
    - $HOME/.pub-cache

jobs:
  include:
    - stage: test
      name: "Linting"
      script: ./flutter/bin/flutter analyze lib/
    # - script: ./flutter/bin/flutter test
    #   name: "Unit Tests"
    # - stage: build
    #   name: "Build Android"
    #   script:
