 
name: Testing
 
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze
